---
- hosts: dev
  user: gt
  become: yes
  gather_facts: yes

  vars:
    pkgname: httpd
    index_path: /var/www/html
  
  tasks:
    - name: install apache
      action: yum pkg="{{pkgname}}" state=present
    - name: start apache service
      action: service name="{{pkgname}}" state=started
    - name: copy index.html
      action: copy src=index.html dest="{{index_path}}"

